### ISSUE TITLE
Lab Report 3 Feedback

### ISSUE THREAD

**Issue by mrkylesmith** [njaurigue/cse15l-lab-reports#3]
Here is your feedback for Lab Report 3 - Streamlining `ssh` Configuration:

- [x] Show your `.ssh/config` file, and how you edited it (with VScode, another program, etc)
- [x] Show the `ssh` command logging you into your account using just the alias you chose.
- [x] Show an `scp` command copying a file to your account using just the alias you chose.

Additional comments from your grader:
I seems as though I cannot view your screenshots on your lab report markdown page.  Also when I click on the image links they appear to be broken links (ie. page not found).  Please submit a regrade request with the screenshot images viewable in your lab report markdown for full credit. 

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by mrkylesmith** [comment]
Hi Noah, 
I see that you made the changes and I can see your screenshots in the lab report now.  Thank you for making these changes, I have updated your score on gradescope.

**Comment by njaurigue** [comment]
Thank you!
